server:
  port: 8888

spring:
  application:
    name: seckill-provider
  ####consul注册中心地址
  cloud:
    consul:
      host: 123.57.140.253
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        prefer-ip-address: true
        heartbeat:
          enabled: true